// The keyword randcase introduces a case statement that randomly selects one its of branches.
module tb;
  initial begin
    $display("random data will be generated by simulator");
    $display("data for 0 to 6 then it will display randcase ouput");
    for (int i=0; i<10; i++) begin
      randcase
      0:$display("output of randcase o");
      1:$display("output of randcase 1");
      2:$display("output of randcase 2");
      3:$display("output of randcase 3");
      4:$display("output of randcase 4");
      5:$display("output of randcase 5");
      6:$display("output of randcase 6");
      endcase
    end
  end
endmodule
/*
# KERNEL: data for 0 to 6 then it will display randcase ouput
# KERNEL: output of randcase 2
# KERNEL: output of randcase 6
# KERNEL: output of randcase 6
# KERNEL: output of randcase 6
# KERNEL: output of randcase 1
# KERNEL: output of randcase 5
# KERNEL: output of randcase 3
# KERNEL: output of randcase 4
# KERNEL: output of randcase 3
# KERNEL: output of randcase 6
# KERNEL: Simulation has finished. There are no more test vectors to simulate.
# VSIM: Simulation has finished.
